#sudo: true
language: ruby
rvm: "2.3.1"
conditions: v0
stages:
  - name: staging
jobs:
  include:
    - stage: staging
      addons:
        artifacts:
          paths:
            - $(git ls-files | tr "\n" ":")
          target_paths:
            - my-test-build/blog
          debug: true
      env:
        - secure: "EH+nZmMyDWUzhVzlN/Dn76u8xpWHpRWJGxOBmzjh4Tm7nf46wYX78n2287K4BUvjo0lo7L1WZ8A0ybr+C36eK5ndHw7VtEj8AFPjKhMMMWBXl97uBCb/ZBuN61WQ/j9Bc1Rm68xmCdLyMfN5OgwUW3p1C5ZmLH8HtIFowmbmwBidkD/VryVxGEis6G1Pwo8LjR/av9qdqyqmwXEa+l8tBh9KAKYcLA6JqTDyCfKbGSFtQhds81kzED71b/8x9cQJHZk5+pfKLJnusMcaItjpyu5JvZbGuzlyjeQ7g1Pd5Qp6KKYJMfred75dx2IwZ2/fKh9gYzonT//pTainnQS9MAvEQEf4QJ1G94rkVLUYVQBBDvHxXRNbxGQ/cMQGH+zcSXULRjCnLiEcBzVhILQJLJcmktZ6Z3IB73cVYnaRfBxbmRPv1B4C1Kxoc2acoQZKPLQ1EC7+OcUruB+Os7A7L2wdJ+Hv9cdWwYMlwVgbiFQW665fps0CBHd7Qwhft0f7iIutF4+QfgQ6NPax3vsS6keXIxUNQkhAJxh7JSPDXG85/8nczb5dzXUoWMEGt75EdpTtcjRhHEVTOURSfF1hPnmIyZ3XSIk8OPtdsmFge6YmLGNmZnyeWdpn7a9C2wiaTwYSu5q4VNe+PNv0qPtwS9S8J9FsVwu5v/GuoBZCfh8="
        - secure: "f2QrrDCxnxLwH4inbv/CgWZZYzwl1zLUfVFjQB0ZvJdbU0mETKlGR1jJ/JHrgh40nN5WW9a3v5qURETt7TlV57QadcsjOPrH+1GP11wKF72dO81YMeLlM1sS8KirSxhl1656YyBiyKtpJr2aWMCs8e/mClFgmKP5nM5tm6zn4iEN9ERF/Nd0rVnMhNsq3lvCtJWSfs3sPfssOg7rkgcLl6gxEW9ys0r5uII0nUcfFW65SBZNlt2US+/hyz/zt+il6rtLr4rya4/XtIQ8r4aGKS+UO/3TCIj0dFyjcv59yxYimWZDpONZPWz1P47jsKbcAlFV8CO2XxXNaUXMX61SqFBYs7E0kq6fqqNkCA6Lcaw6+YT1r3JtOgNaR7lMdpDT9f7kZuGU05Bhq4GtsSLtXEsdriI+LSu6/dfgk7xfHJU2Gh2VQfAcNfcVd/DQyzRqiwPiFyn06jeDabvnmCx5LQZNPub+irLJtL8Oa3M8ciWLu7UMqKubqsAn28/J0XrYVc/DGlueb5HR+4WRdbU9yGA7CjGQe43bQ1SfZduMQHR5rN7eeo28TzNW0Ac1y/RddN2no3ommPY0sm63gvFM1AhnZk6KyH+5ch5woiCZrJ4QC6VQuZ/sPJXau2HbBCmLhUA1nV23C+SAItAQxHy1CB5pJr18Lp2c3MDZu39VZXg="
        - secure: "bByUPkqzM37br6s6MIKV2PtjoepWh4Y89a/I6FmoAVtgGKqYC/d57ENnUdUbPapg4MmvsvSmmtlt2+qq93SdKly4XPGW9fGK/p/84Mo/RUlFUhwJVDM85zexfzDvm05YMcYsLcYKSssW55HImdhK2TKc9pYXEsucVTpbBDsLZyBOeuOUlPk2aIjDrdzkSfIPOH5KgnBAXLYRj/E90SufyNc346qIjFgJQ12muXQtq+JK5/ivu8/fnAnnnqEhp2LP/Wmt8L+6nv0/MgxCapjbeOPUbXQADc6vvYS7XVbEH73c5NyUEcYLhJ1Papb+ka6zK8USDQnGX8vPFsSRnWUqAPsBTWckEhQkP2eQurxuhJJr807C5SMtn2ZL5zpPfuQ4FzNOHRLCbKdmvfiayjhF6/Zu+wKz6IxFBOj90dh/NWK0Kk8oRD6IAHaFmEpirMQWFUCs8n62tgmPcVnB24PWCJps0/NsArDL8TbGeYcXGYPxbCvK0uVym1A1s6WYvTChaeM9fOrT/ZF6KFo6ruPaaPzIl3e+WhJbIEsS+TNAjQ8WMbqs11d0WT/sXghEdDbc4JmQSuf+BlozjYzuWTFf4VQJtXV7gRDMN3kfVFAQz+4SdvvICN3vQdO/VVlWXvp65BpfeYpoCjZFh7EDNnEeilLusJlUkRQ9yVJOJHg6Aak="  
        - secure: "d6cq5ysn5fGnT25AIO3L7E8u1wq+8j+Z9m2BEaWaxra1Eqb+zuH6wyDEHk4N2z2UviE2hSnz11sRj8iRItEmGZquNLRsPxqazX/KSqR3ikW91Rztf62J71mz943Xef1O1OeagSDwnLkLhBKu5kKYVMkXUJ1eQ2aGUGBth9Xc0zL2GIxEDC7TPxkjfDGW2nmQkTkkuo6mWsSdOgY0+F7B7T01exGZUiYj8E+Vh8DCnLgt1L4ITzDhPUrQn2Et8nyhm63YNbNOCDQhawQSVXPOxlyORPg6JY9bTzao31bkdLioKW/HZmoKZTaV13/sty92nEstv6JrgzozsuN9XmN+5P6sYJ7iRs6tdboMKrMH+XWpO4RGGswlri4v3gKgfG6tAIhWsh550pT7+6XTBZPLmceTZmGgpxu+oFbrzGbr6DX5F+Ko69Ss4kV+0Jj6DtzVzJnQbBEHWz763Xgi22OXHmCCmkm+mjkzS5WqydMUqlagUZe0rijL6JDmDPIuHFO6WsoTZ844Us3wibLbp2HEHh1CBhlT72XnkS33s/lG7Dl7wwh4MwjBeORZh8IndW/WMwcAMKd//lF9RhcM+qSAvjenoWgM4jFQFMxonmQ7jAK0mnAQ5PRgREN8b2gQR1LLy2l+k7l0hIX3H3TjBU7WfTk1/kSI6qmdpJfrpH1yIBo="
        - secure: "d8vnmOprC79XvTqREe63z7iA1XUx+FnrKL9BQqAkDlzF6dltwxpiJ2houlYfAanbnFnucJK3Jqhwa+1NDKgloFE0t0lF6dHmNpOcxR0zIXC4tTFpmCNgC3H2Qf2sSZafGUEzU9xdz0sUHErjMIFd3MK4ZSSYNPRpwM9Io+F8ALZkDJJZilkWZ7TvLeYoNjoqqPNswhV2bKiOG75ZqtXEF7fes5gulQgEmtWje/if5pR5qJ4yopaUi7NLWA/236gakZTsW3Cymu/alQaVPHhYiYg070mWrBriuty9w6dz7rzu1kHeMi4y7wLJNCBcHFwmhPKrKMmRHA+JKcaHsXA7zQUU5ZJ5whz5DbgEKnv3pFE1EP9FHBYPwsg3cwuB5CDIKbIcFEFvA1btdQlMMGMW3qyb4tGv5g2kMshz/knEWmFvspCXpGNJcC8YXbrJg3tdXuBBs64JcrWMcTTNjCLBuQ7h8sl63eweqVQgwr6XpFV8qnRKSNc6L+3RMdPJ7teBeLDkutX08VOsyHWnYdmvYQEFYEhMEH78NU8CBQBa6WDc6UIkII0cEkXjT2rZg1hm4SE6g2YJiJWyusbWD4R8lBrp0nrbqy1U0YeYh3jEF1QbBoFuf+S1x8Gu1Z5oCoRQohVOk93b8Cc4GwXBeJ5Vl3/MwnLxFOk9C9uubvLJRys="
      if: branch =~ /^travis_aws_code_deploy*/
      before_script: 
        - cd blog
      script:
        - bundle install
        - bundle exec rspec
      deploy:  
        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: "mdn-codedeploy-artifact"
          key: my-test-build/latest/artifact.zip
          bundle_type: zip
          application: mdn-codedeploy
          deployment_group: mdn_deployment_group
          on:
            all_branches: true

