language: ruby
rvm:
  - 2.3.1
before_install:
  - openssl aes-256-cbc -K $encrypted_43cbdd85bbec_key -iv $encrypted_43cbdd85bbec_iv -in super_secret.txt.enc -out super_secret.txt -d
  - cat super_secret.txt
before_script:
  - cd blog
script: 
  - bundle install
  - bundle exec rspec

