#sudo: true
language: ruby
rvm: "2.3.1"
conditions: v0
stages:
  - name: staging
jobs:
  include:
    - stage: staging
      addons:
        artifacts:
          paths:
            - $(git ls-files | tr "\n" ":")
          target_paths:
            - my-test-build/blog
          debug: true
      env:
        - secure: "EH+nZmMyDWUzhVzlN/Dn76u8xpWHpRWJGxOBmzjh4Tm7nf46wYX78n2287K4BUvjo0lo7L1WZ8A0ybr+C36eK5ndHw7VtEj8AFPjKhMMMWBXl97uBCb/ZBuN61WQ/j9Bc1Rm68xmCdLyMfN5OgwUW3p1C5ZmLH8HtIFowmbmwBidkD/VryVxGEis6G1Pwo8LjR/av9qdqyqmwXEa+l8tBh9KAKYcLA6JqTDyCfKbGSFtQhds81kzED71b/8x9cQJHZk5+pfKLJnusMcaItjpyu5JvZbGuzlyjeQ7g1Pd5Qp6KKYJMfred75dx2IwZ2/fKh9gYzonT//pTainnQS9MAvEQEf4QJ1G94rkVLUYVQBBDvHxXRNbxGQ/cMQGH+zcSXULRjCnLiEcBzVhILQJLJcmktZ6Z3IB73cVYnaRfBxbmRPv1B4C1Kxoc2acoQZKPLQ1EC7+OcUruB+Os7A7L2wdJ+Hv9cdWwYMlwVgbiFQW665fps0CBHd7Qwhft0f7iIutF4+QfgQ6NPax3vsS6keXIxUNQkhAJxh7JSPDXG85/8nczb5dzXUoWMEGt75EdpTtcjRhHEVTOURSfF1hPnmIyZ3XSIk8OPtdsmFge6YmLGNmZnyeWdpn7a9C2wiaTwYSu5q4VNe+PNv0qPtwS9S8J9FsVwu5v/GuoBZCfh8="
        - secure: "f2QrrDCxnxLwH4inbv/CgWZZYzwl1zLUfVFjQB0ZvJdbU0mETKlGR1jJ/JHrgh40nN5WW9a3v5qURETt7TlV57QadcsjOPrH+1GP11wKF72dO81YMeLlM1sS8KirSxhl1656YyBiyKtpJr2aWMCs8e/mClFgmKP5nM5tm6zn4iEN9ERF/Nd0rVnMhNsq3lvCtJWSfs3sPfssOg7rkgcLl6gxEW9ys0r5uII0nUcfFW65SBZNlt2US+/hyz/zt+il6rtLr4rya4/XtIQ8r4aGKS+UO/3TCIj0dFyjcv59yxYimWZDpONZPWz1P47jsKbcAlFV8CO2XxXNaUXMX61SqFBYs7E0kq6fqqNkCA6Lcaw6+YT1r3JtOgNaR7lMdpDT9f7kZuGU05Bhq4GtsSLtXEsdriI+LSu6/dfgk7xfHJU2Gh2VQfAcNfcVd/DQyzRqiwPiFyn06jeDabvnmCx5LQZNPub+irLJtL8Oa3M8ciWLu7UMqKubqsAn28/J0XrYVc/DGlueb5HR+4WRdbU9yGA7CjGQe43bQ1SfZduMQHR5rN7eeo28TzNW0Ac1y/RddN2no3ommPY0sm63gvFM1AhnZk6KyH+5ch5woiCZrJ4QC6VQuZ/sPJXau2HbBCmLhUA1nV23C+SAItAQxHy1CB5pJr18Lp2c3MDZu39VZXg="
        - secure: "bByUPkqzM37br6s6MIKV2PtjoepWh4Y89a/I6FmoAVtgGKqYC/d57ENnUdUbPapg4MmvsvSmmtlt2+qq93SdKly4XPGW9fGK/p/84Mo/RUlFUhwJVDM85zexfzDvm05YMcYsLcYKSssW55HImdhK2TKc9pYXEsucVTpbBDsLZyBOeuOUlPk2aIjDrdzkSfIPOH5KgnBAXLYRj/E90SufyNc346qIjFgJQ12muXQtq+JK5/ivu8/fnAnnnqEhp2LP/Wmt8L+6nv0/MgxCapjbeOPUbXQADc6vvYS7XVbEH73c5NyUEcYLhJ1Papb+ka6zK8USDQnGX8vPFsSRnWUqAPsBTWckEhQkP2eQurxuhJJr807C5SMtn2ZL5zpPfuQ4FzNOHRLCbKdmvfiayjhF6/Zu+wKz6IxFBOj90dh/NWK0Kk8oRD6IAHaFmEpirMQWFUCs8n62tgmPcVnB24PWCJps0/NsArDL8TbGeYcXGYPxbCvK0uVym1A1s6WYvTChaeM9fOrT/ZF6KFo6ruPaaPzIl3e+WhJbIEsS+TNAjQ8WMbqs11d0WT/sXghEdDbc4JmQSuf+BlozjYzuWTFf4VQJtXV7gRDMN3kfVFAQz+4SdvvICN3vQdO/VVlWXvp65BpfeYpoCjZFh7EDNnEeilLusJlUkRQ9yVJOJHg6Aak="  
        - secure: "wTQN9PPRYQKZYu0wuYIf4LTIH0T334caIGyzQbceE8F+tNol8UvEqL4cGvgZW5UaWb6GafjHRtHtz7itvAOZwW0tJ9CAMAtpX1LTZb5oXxneAH99Z9VD9bFuVlkmwq2oHuAAaJpQIhMjk4qSI2N9Jhj3ylOBzNpR8u+62GHwjSQSv/YY3FQ5Gz08kSHMRiHy/gOI4XLaxCHLWDmk/Z1dxwteVagFTEYm3Bs/YGozV/cew88TkcWm6dc5tdIblD/NjxvpjIDmarA/MusMlt4QpxdkeFCRLM02QVIE2X3aSIhhk42X2u1yKwqoDI2wJmPgHdBhHpisly/i80jegcL37vJ+t596VBoE90TpvFHUj30dxf3G/3o5f3KX/2a6g/wHLQ9gGqgTy51TmXV0XDq7DPce1A2OmuHZy/GW5F0DB85nEpekmGwXpVgOvIBNWEUYAXYhz9aYh42wIRfrCQXQMmagPDEI6ImInTMOnSbnFwLu+LJlzDyj9BuJ7vaeZ/eBd3dbWlxOHGqeSKoauqqRlu8fOrEFCDmIxEpYtSFqIyBRJaZzmDI7qO7C913QOe1V4qqAJbocYtx+VycI7WDFdZwIbsXhFk3y3ffSd3fLLeIX34zHzYziCog3TB3+SKf+41qNPSsRuGj4uE/YRdNWFKdthfzTbCb1fIdwv75Bwfc="
        - secure: "YVD4678udG/lisYsXB3Jcdu6mdYLZ1LXlI7Mw2TFdfxKD2fnNMj532SxukvMKYz7+kYGjbOHuIHzcHEitKooM3OHgiYKSrwbEWg/hM9PKhRezzek9MDAs9gjlwAPuAWzpDHNL1PzL1IGdHJSC+n1GD1tivNrSh50MQATg9prppf45vYO64XTaqncs3sHKUweOnR6wCtYJ0ycVJjE7aiM50bh1F9tgkM11V2zYHXDQtlklqVM2ofmBp4t7gglKRzrU88IeFYV1wi5HXgqp3nPITv+Z+eBFyZGHfMXO8pz7oK7dGW1U97ao/zSYnf+IBm+6pTkagw3y+ehvnnrBMkNQCW4SNNhyFro4kGKJeTX0psCymMI0by/GYFsLfpZy6JankLGnXzyIX8qgamH+Blg0Kftv1aT1hqrp5G93MoLDcnIBDxLbqldoFFanT0TcLfyg9beV22DOeTv1MxwLxhLrN+1QSFXa2Z5JoIXToYyDdYlCUOaxe10/G23xzdf/kHrH8fpkIbV8ysn0nXKmXD/5bR4/abx0t58sv8m1FMG/pxce5Z3LRPoMXNLAoLH4n0ih7JEFGvPD3Efpxw51+dFF8GvOVFwIFujtJblMIF4XEcDM9MDsf0Z585xI/PxDp6D7npHfPbfsRPzmfE41cverCJlwwMpQmWOS3LXmKajS9k="
      if: branch =~ /^travis_aws_code_deploy*/
      before_script: 
        - cd blog
      script:
        - bundle install
        - bundle exec rspec
      deploy:  
        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: "mdn-codedeploy-artifact"
          key: my-test-build/latest/artifact.zip
          bundle_type: zip
          application: mdn-codedeploy
          deployment_group: mdn_deployment_group
          on:
            all_branches: true

