language: ruby
# the following line is needed to enable the TravisCI build conditions
rvm:
  - 2.3.1
conditions: v1
stages:
  -name: unit test
    if: branch = dev_master
  -name: deploy on prod
    if: branch = master
jobs:
  include:
    - stage: unit test
      before_script: 
        - cd blog
      script:
        - bundle install
        - bundle exec rspec
    - stage : deploy on prod
      before_install:
        - openssl aes-256-cbc -K $encrypted_43cbdd85bbec_key -iv $encrypted_43cbdd85bbec_iv -in blog/mdn-mysql-own.pem.enc -out blog/mdn-mysql-own.pem -d
        - chmod 600 blog/mdn-mysql-own.pem
        - cat blog/mdn-mysql-own.pem
        - eval "$(ssh-agent -s)"
        - ssh-add blog/mdn-mysql-own.pem
      install:
        - echo 'amazonaws.com,100.27.38.68 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG4W/WtjgGSPQdLthvsT9Vu2UZtEv9SRusr87+dxx8zENXfuAmiSYFf9Y3p7mMGKylTF5RscoWv3hNKq29sJhBCam81MJfuW30SBtRwVgvNiJ7WCAPyFJnIbqxJyTuM3bjX5BvoQGPuL2VjBc+opBHZtxV5EbrNJpmmd6C1afaX8wMMhpwgHoCO1mexofq+1OkDACwrSXVEJP/MaIhMUWqt8F45eJXZTf8JfdlAQsC8qofpcc9Iqy45qrkswTrBL6WGWllhITIX8kewl8bxYw4UGsYab0nIN8pEA2y04/CKeDFumIPtCgyOt0p0/XH1PYrkVXeHCW1ISXn3YmqFN2X==' >> ${TRAVIS_HOME}/.ssh/known_hosts
        - cat ${TRAVIS_HOME}/.ssh/known_hosts
      addons:
        ssh_known_hosts: 
          - 172.31.15.186
          - 100.27.38.68
      deploy:
        - provider: script
          script: bash scripts/deploy.sh