language: ruby
# the following line is needed to enable the TravisCI build conditions
rvm:
  - 2.3.1
conditions: v0
stages:
  - name: unit test
  - name: deploy on prod
jobs:
  include:
    - stage: unit test
      env:
        - secure: "IRMkFRBEGWDC62tqC3dMywrxHKfYBAKVbdRE13wfNN6Exj5agAcquRf8PcSLDoIl8/pe5Hm353tiKTuqayuuQ1TRjjJRQoZBzB5fL4yTvOnbfhbVmCsTDeYI9DzZRm/uaZGjRbQZ01SipphUdn8OjXXSzypQNiqP2rjwMIo8cdMmUVqkIGJ150aZUDiOvbXjOSdEroWn8i6Q5cVi9oDynJSvuXqUtvg9ICQ0WSTwVKVvBnuy3HGMMA17SqxMlDpULDYGdPcySyHRquoAq6L6O2jkoKS4QHGPgg6tE2krFxuyCMRu5x1+88E2JN8GA+8L2nQVa5jAnJvnZUSlBPHuoa6RdbCL9ZnJsc2BZjvekRHk7Z4ES92JcFBynhrF5hzgM8P8AKp3lGKtUm6ZReaThiB2lB18FoGXTsKCkDMENeOugCqOZSomApe0TrQfuRPID5LrzI99fAkSEvpx/thvvbJ7K1pbTrfGHJibEf4/bqIT1f/gyyjd/wf3EnBB2tpIR7yvV7d+53j4ekN1Aj+jKW/xcy/vXZ11nyhLyIYXYHvufRAx9o4MZj374B1OtrYrffDHrJOsMbD5nm1Om/jsd019sPIpUipBMMY/ngjZXONlpPDCKpTRtZasKo1qyEDGKjAuYTcXulc4JPPSs8QxgHJ3zA0RGqP4zd/k519Xwd0="
      if: branch =~ /^developer*/
      before_script: 
        - cd blog
      script:
        - bundle install
        - bundle exec rspec
        - bash scripts/loc.sh
        - echo "printing encrypted value"
        - echo $DUMMY_KEY_TEST
    - stage: deploy on prod
      if: branch = master
      before_install:
        - openssl aes-256-cbc -K $encrypted_43cbdd85bbec_key -iv $encrypted_43cbdd85bbec_iv -in blog/mdn-mysql-own.pem.enc -out blog/mdn-mysql-own.pem -d
        - chmod 600 blog/mdn-mysql-own.pem
        - cat blog/mdn-mysql-own.pem
        - eval "$(ssh-agent -s)"
        - ssh-add blog/mdn-mysql-own.pem
      install:
        - echo 'amazonaws.com,100.27.38.68 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG4W/WtjgGSPQdLthvsT9Vu2UZtEv9SRusr87+dxx8zENXfuAmiSYFf9Y3p7mMGKylTF5RscoWv3hNKq29sJhBCam81MJfuW30SBtRwVgvNiJ7WCAPyFJnIbqxJyTuM3bjX5BvoQGPuL2VjBc+opBHZtxV5EbrNJpmmd6C1afaX8wMMhpwgHoCO1mexofq+1OkDACwrSXVEJP/MaIhMUWqt8F45eJXZTf8JfdlAQsC8qofpcc9Iqy45qrkswTrBL6WGWllhITIX8kewl8bxYw4UGsYab0nIN8pEA2y04/CKeDFumIPtCgyOt0p0/XH1PYrkVXeHCW1ISXn3YmqFN2X==' >> ${TRAVIS_HOME}/.ssh/known_hosts
        - cat ${TRAVIS_HOME}/.ssh/known_hosts
      addons:
        ssh_known_hosts: 
          - 172.31.15.186
          - 100.27.38.68
      deploy:
        - provider: script
          script: bash scripts/deploy.sh