language: ruby
# the following line is needed to enable the TravisCI build conditions
rvm:
  - 2.3.1
conditions: v0
stages:
  - name: unit test
  - name: deploy on prod
jobs:
  include:
    - stage: unit test
      env:
        - secure: "L+7Gkra6st9Fj6Q3MJYh/wOmSzsYcahq2UyGqgZGgvHpAdclnT9S51VNBXWd4jTQIc0E94LF5HoiTQ7QjDD07uEfJBqYeY95jA3CBi0llGuDztfQPbibc3wHGNSU7F1lDOn0yCJ1TuoZPjkHIOAYMN9OE9mxSsP6mz0l7fgwTLvHX7Ypu12dBHzqGVJQlNepTurKPAgBMbcW2sg0eSpt7Uzcdk9O+wKhlBgQZPyCtMd6o2QEh5EAwG9I6eMvb4UVy0n4uL9dJ4F+0H9gZRxFeP04Qo20XCqiONDtwSUWsNOMQqfBze3VuAoGlGp6kXitvoCsV9suDUEYAlj5DYeT6CCVQkamdvpAkuus+4SbNKxFBlI8HzTL5gPCgst8v2UfufXrql6+/boeWkHR9mMC60lLJTaUcpHVIm4a0/VxDyEZ2xHGiNjz2MLCFNFjJR+YOPsuIu/hxlihUiW68L5aYeqmxztUEn8zqPPWc8n3DQzwIGzZYuKM2MsioZGcT4+dZ/SMR9v8hyypZBHYa/hoepd8RJq3UTVuj42hHo/XXXqcOhvH2ECmZvL/JYN8yk7pjYhSfx8hlGkTUKCC+Qepi9vr04S9JZ/FpCR0aV+JWao0bB1WnlDrVAwfz2dmxsYV3OIy98k+ji6tLCPxW/R5MSVOH3iYpH++T9qqWYbaeT8="
      if: branch =~ /^developer*/
      before_script: 
        - cd blog
      script:
        - bundle install
        - bundle exec rspec
        - bash scripts/loc.sh
    - stage: deploy on prod
      if: branch = master
      before_install:
        - openssl aes-256-cbc -K $encrypted_43cbdd85bbec_key -iv $encrypted_43cbdd85bbec_iv -in blog/mdn-mysql-own.pem.enc -out blog/mdn-mysql-own.pem -d
        - chmod 600 blog/mdn-mysql-own.pem
        - cat blog/mdn-mysql-own.pem
        - eval "$(ssh-agent -s)"
        - ssh-add blog/mdn-mysql-own.pem
      install:
        - echo 'amazonaws.com,100.27.38.68 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG4W/WtjgGSPQdLthvsT9Vu2UZtEv9SRusr87+dxx8zENXfuAmiSYFf9Y3p7mMGKylTF5RscoWv3hNKq29sJhBCam81MJfuW30SBtRwVgvNiJ7WCAPyFJnIbqxJyTuM3bjX5BvoQGPuL2VjBc+opBHZtxV5EbrNJpmmd6C1afaX8wMMhpwgHoCO1mexofq+1OkDACwrSXVEJP/MaIhMUWqt8F45eJXZTf8JfdlAQsC8qofpcc9Iqy45qrkswTrBL6WGWllhITIX8kewl8bxYw4UGsYab0nIN8pEA2y04/CKeDFumIPtCgyOt0p0/XH1PYrkVXeHCW1ISXn3YmqFN2X==' >> ${TRAVIS_HOME}/.ssh/known_hosts
        - cat ${TRAVIS_HOME}/.ssh/known_hosts
      addons:
        ssh_known_hosts: 
          - 172.31.15.186
          - 100.27.38.68
      deploy:
        - provider: script
          script: bash scripts/deploy.sh