version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: scripts
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - file    
hooks:
  AfterInstall:
    - location: scripts/rails_server_startup.sh
      timeout: 30000
      runas: ubuntu